version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Create virtualenv
          command: |
            pip3 install virtualenv
            virtualenv -p $(which python3) ~venvpy3
            source ~venvpy3/bin/activate
            pip install -r requirements.txt
      - setup_remote_docker       
workflows:
  main:
    jobs:
      - build-and-test
  # the nightly workflow is configured to run every day at 12:00am UTC. 
  # The cron key is specified using POSIX crontab syntax, see the crontab man page for cron syntax basics. 
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master