version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Create virtualenv
          command: |
            python -V
            python3 -V
            pip3 --version
            pip3 install virtualenv
            virtualenv -p $(which python3) ~venvpy3
            source ~venvpy3/bin/activate
            pip install -r requirements.txt
  build-minikube:
    # docker:
    #   - image: circleci/ruby:2.4-node 
    executor: python/default         
    steps:
      - setup_remote_docker
        #  docker_layer_caching: true            
      - run:
          name: Deploy minikube latest
          command: |
            echo "=============================deploy kubectl============================================================="
            # sudo make deploy-minikube-latest          
  build-argocd:
    # docker:
    #   - image: circleci/ruby:2.4-node
    executor: python/default          
    steps:
      - run:
          name: Deploy argocd
          command: |
            echo "===============================deploy argocd finished==========================================================="
            # sudo make deploy-argocd  

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build-and-test
      - build-minikube
      - build-argocd
  scheduled-workflow:
    triggers:
      - schedule:
          # cron: "0 1 * * *"
          # an hourly cron job but run at minute 15 instead (i.e. 00:15, 01:15, 02:15 etc.)
          cron: "15 * * * *"
          filters:
            branches:
              only: 
              - dev

    jobs:
      - build-and-test
      - build-minikube
      - build-argocd
